Repository malparty/nimbleat, pull requests merged in 2022-09, with the labels that each got.

#12 [UI] As a user I can click on the pads to call the "playPad"
  app/favicon.ico
  app/index.html
  app/javascript/components/pad/index.js
  app/javascript/index.js
  app/javascript/screens/base.js
  app/javascript/screens/index.js
  app/synth.html
  package-lock.json
  package.json
Labels: Feature, UI

#13 [#5] [UI] When a valid key is pressed, the function playPad is called with the pad id
  app/javascript/components/pad/index.js
  app/javascript/screens/base.js
  app/javascript/utilities/keyMap.js
  app/styles/application.css
  app/styles/components/index.css
  app/styles/components/pad.css
  app/styles/tailwind.css
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: Feature, UI, High priority

#15 Add the sound engine file structure
  app/javascript/components/pad/index.js
  app/javascript/screens/base.js
  app/javascript/sound-engines/index.js
  app/javascript/sound-engines/sampler-engine.js
  app/javascript/sound-engines/wave-table-engine.js
  app/styles/components/pad.css
Labels: Chore

#16 [#10] [Backend] When in synth mode, I can play different notes of an instrument
  .gitignore
  .prettierrc.js
  app/assets/samples/drum.wav
  app/assets/samples/girl-scream.wav
  app/assets/samples/piano.wav
  app/javascript/sound-engines/sampler-engine.js
  package-lock.json
  package.json
Labels: Backend

#17 Add wave table sound engine
  app/javascript/components/synthVoice/samples/wave-tables/Bass_Fuzz_2.js
  app/javascript/components/synthVoice/samples/wave-tables/TwelveStringGuitar1.js
  app/javascript/components/synthVoice/samples/wave-tables/index.js
  app/javascript/screens/base.js
  app/javascript/sound-engines/index.js
  app/javascript/sound-engines/wave-table-engine.js
  app/javascript/utilities/scales.js
  app/styles/components/pad.css
Labels: Feature

#18 [#9] [Backend] When in Synth mode, I can play an instrument sound
  app/assets/samples/girl-scream.wav
  app/assets/samples/goat-scream.mp3
  app/javascript/sound-engines/sampler-engine.js
Labels: Feature
